SearchBayesianSkopt: Resuming 'SLIM_BPR_Recommender' Failed, no such file exists.
SearchBayesianSkopt: New best config found. Config 0: {'topK': 990, 'epochs': 55, 'symmetric': False, 'sgd_mode': 'adam', 'lambda_i': 0.0007615480878340148, 'lambda_j': 0.0005239750169069712, 'learning_rate': 0.034375390875555176} - results: PRECISION: 0.0312954, PRECISION_RECALL_MIN_DEN: 0.0682205, RECALL: 0.0665375, MAP: 0.0138073, MAP_MIN_DEN: 0.0300180, MRR: 0.1070001, NDCG: nan, F1: 0.0425689, HIT_RATE: 0.2410029, ARHR_ALL_HITS: 0.1211741, NOVELTY: 0.0037364, AVERAGE_POPULARITY: 0.3947083, DIVERSITY_MEAN_INTER_LIST: 0.6987204, DIVERSITY_HERFINDAHL: 0.9698702, COVERAGE_ITEM: 0.4632554, COVERAGE_ITEM_HIT: 0.0218305, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.2253717, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0218052, SHANNON_ENTROPY: 6.8299882, RATIO_DIVERSITY_HERFINDAHL: 0.9703229, RATIO_DIVERSITY_GINI: 0.0500130, RATIO_SHANNON_ENTROPY: 0.5183042, RATIO_AVERAGE_POPULARITY: 6.4562963, RATIO_NOVELTY: 0.4297978, 
SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 990, 'epochs': 55, 'symmetric': False, 'sgd_mode': 'adam', 'lambda_i': 0.0007615480878340148, 'lambda_j': 0.0005239750169069712, 'learning_rate': 0.034375390875555176} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 1: {'topK': 888, 'epochs': 145, 'symmetric': False, 'sgd_mode': 'sgd', 'lambda_i': 5.5192736267219694e-05, 'lambda_j': 0.006800245937235813, 'learning_rate': 0.00042365472862800096} - results: PRECISION: 0.0308664, PRECISION_RECALL_MIN_DEN: 0.0679345, RECALL: 0.0663195, MAP: 0.0135641, MAP_MIN_DEN: 0.0298453, MRR: 0.1059428, NDCG: nan, F1: 0.0421264, HIT_RATE: 0.2395900, ARHR_ALL_HITS: 0.1195247, NOVELTY: 0.0037027, AVERAGE_POPULARITY: 0.4078657, DIVERSITY_MEAN_INTER_LIST: 0.6726171, DIVERSITY_HERFINDAHL: 0.9672600, COVERAGE_ITEM: 0.4411393, COVERAGE_ITEM_HIT: 0.0193414, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.2240505, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0196669, SHANNON_ENTROPY: 6.6417077, RATIO_DIVERSITY_HERFINDAHL: 0.9677114, RATIO_DIVERSITY_GINI: 0.0451085, RATIO_SHANNON_ENTROPY: 0.5040163, RATIO_AVERAGE_POPULARITY: 6.6715132, RATIO_NOVELTY: 0.4259161, 
SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 888, 'epochs': 145, 'symmetric': False, 'sgd_mode': 'sgd', 'lambda_i': 5.5192736267219694e-05, 'lambda_j': 0.006800245937235813, 'learning_rate': 0.00042365472862800096} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 2: {'topK': 241, 'epochs': 30, 'symmetric': False, 'sgd_mode': 'sgd', 'lambda_i': 1.0794063441097047e-05, 'lambda_j': 0.00037797458085869317, 'learning_rate': 0.0002611662337117542} - results: PRECISION: 0.0309949, PRECISION_RECALL_MIN_DEN: 0.0677091, RECALL: 0.0660698, MAP: 0.0137600, MAP_MIN_DEN: 0.0299342, MRR: 0.1068914, NDCG: nan, F1: 0.0421951, HIT_RATE: 0.2390506, ARHR_ALL_HITS: 0.1208816, NOVELTY: 0.0038038, AVERAGE_POPULARITY: 0.3735834, DIVERSITY_MEAN_INTER_LIST: 0.7340945, DIVERSITY_HERFINDAHL: 0.9734076, COVERAGE_ITEM: 0.5350308, COVERAGE_ITEM_HIT: 0.0213816, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.2235461, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0298151, SHANNON_ENTROPY: 7.1506110, RATIO_DIVERSITY_HERFINDAHL: 0.9738619, RATIO_DIVERSITY_GINI: 0.0683847, RATIO_SHANNON_ENTROPY: 0.5426352, RATIO_AVERAGE_POPULARITY: 6.1107529, RATIO_NOVELTY: 0.4375518, 
SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 241, 'epochs': 30, 'symmetric': False, 'sgd_mode': 'sgd', 'lambda_i': 1.0794063441097047e-05, 'lambda_j': 0.00037797458085869317, 'learning_rate': 0.0002611662337117542} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 3: {'topK': 523, 'epochs': 25, 'symmetric': True, 'sgd_mode': 'adam', 'lambda_i': 0.00011344167078264487, 'lambda_j': 0.00020294438510099302, 'learning_rate': 0.0011873782012305995} - results: PRECISION: 0.0328444, PRECISION_RECALL_MIN_DEN: 0.0716911, RECALL: 0.0699372, MAP: 0.0146932, MAP_MIN_DEN: 0.0318866, MRR: 0.1126922, NDCG: nan, F1: 0.0446976, HIT_RATE: 0.2500706, ARHR_ALL_HITS: 0.1282185, NOVELTY: 0.0038842, AVERAGE_POPULARITY: 0.3585893, DIVERSITY_MEAN_INTER_LIST: 0.7594778, DIVERSITY_HERFINDAHL: 0.9759458, COVERAGE_ITEM: 0.5725303, COVERAGE_ITEM_HIT: 0.0267679, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.2338514, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0380886, SHANNON_ENTROPY: 7.5125969, RATIO_DIVERSITY_HERFINDAHL: 0.9764013, RATIO_DIVERSITY_GINI: 0.0873609, RATIO_SHANNON_ENTROPY: 0.5701050, RATIO_AVERAGE_POPULARITY: 5.8654925, RATIO_NOVELTY: 0.4467979, 
SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 523, 'epochs': 25, 'symmetric': True, 'sgd_mode': 'adam', 'lambda_i': 0.00011344167078264487, 'lambda_j': 0.00020294438510099302, 'learning_rate': 0.0011873782012305995} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: New best config found. Config 4: {'topK': 883, 'epochs': 45, 'symmetric': False, 'sgd_mode': 'adam', 'lambda_i': 1.0033911167429343e-05, 'lambda_j': 0.0008647053260643572, 'learning_rate': 0.0001017414744512981} - results: PRECISION: 0.0313288, PRECISION_RECALL_MIN_DEN: 0.0686249, RECALL: 0.0669509, MAP: 0.0137503, MAP_MIN_DEN: 0.0300341, MRR: 0.1067578, NDCG: nan, F1: 0.0426842, HIT_RATE: 0.2418249, ARHR_ALL_HITS: 0.1207626, NOVELTY: 0.0037290, AVERAGE_POPULARITY: 0.3985030, DIVERSITY_MEAN_INTER_LIST: 0.6892798, DIVERSITY_HERFINDAHL: 0.9689262, COVERAGE_ITEM: 0.4696617, COVERAGE_ITEM_HIT: 0.0208104, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.2261404, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0220362, SHANNON_ENTROPY: 6.7756604, RATIO_DIVERSITY_HERFINDAHL: 0.9693784, RATIO_DIVERSITY_GINI: 0.0505428, RATIO_SHANNON_ENTROPY: 0.5141815, RATIO_AVERAGE_POPULARITY: 6.5183669, RATIO_NOVELTY: 0.4289415, 
SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 883, 'epochs': 45, 'symmetric': False, 'sgd_mode': 'adam', 'lambda_i': 1.0033911167429343e-05, 'lambda_j': 0.0008647053260643572, 'learning_rate': 0.0001017414744512981} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchBayesianSkopt: Search interrupted due to ValueError. The evaluated configurations may have had all the same value.
SearchBayesianSkopt: Extending previous number of cases from 15 to 25.
